name: housing
dependencies:
    - python=3.5
    - numpy=1.11.1
    - pandas=0.18.1
    - scikit-learn=0.18.1
    - seaborn=0.7.1
    - theano=0.8.2
    - ipython
    - jupyter
    - pip:
        - keras==1.2
